### ISSUE TITLE
Plogging Api

### ISSUE THREAD

**Issue by melitina915** [plog-us/plog-us-BE#2]
## ✅ Checklist
- [ ] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성

## ✏ Description
- Plogging
    - 플로깅 기록 리스트 / 세부 기록
    - 플로깅 종료 후 저장

- 프로필 사진 수정, OAuth는 추후 구현

## 📋 TODO
- [ ] 플로깅 기록 리스트
- [ ] 플로깅 세부 기록
- [ ] 플로깅 종료 후 저장
