### ISSUE TITLE
Quiz Api

### ISSUE THREAD

**Issue by melitina915** [plog-us/plog-us-BE#4]
## ✅ Checklist
- [ ] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성

## ✏ Description
- Quiz
    - 퀴즈 점수 + 1

## 📋 TODO
- [ ] 퀴즈 정답 맞힌 경우 +1
