### ISSUE TITLE
Leaderboard Api

### ISSUE THREAD

**Issue by melitina915** [plog-us/plog-us-BE#5]
## ✅ Checklist
- [ ] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성

## ✏ Description
- Leaderboard
    - 플로깅 랭킹
    - 퀴즈 랭킹

## 📋 TODO
- [ ] 플로깅 랭킹 : username, ploggingScore
- [ ] 퀴즈 랭킹 : username, quizScore
