### ISSUE TITLE
Plogphotos Api

### ISSUE THREAD

**Issue by melitina915** [plog-us/plog-us-BE#9]
## ✅ Checklist
- [ ] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성

## ✏ Description
- 플로깅 사진 관련 기능

## 📋 TODO
- [ ] 플로깅 사진 추가
